
image:
  repository: gitlab.desy.de:5555/dcache/dcache
  tag: ""
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent


dcache:
  pools:
    - a
    - b
    - c 

cell:
  tunnel: 11111

door:
  ports:
    nfs: 2049
    xrootd: 1094
    webdav: 8080

mover:
  nfs: 32049
  xrootd: 31094
  http: 38080