
image:
  registry: docker.io
  repository: dcache/dcache-test
  tag: ""
  digest: ""
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: []
  ## Enable debug mode
  ##
  debug: false


dcache:
  pools:
    - a
    - b
    - c 

cell:
  tunnel: 11111

door:
  ports:
    nfs: 2049
    xrootd: 1094
    webdav: 8080

mover:
  nfs: 32049
  xrootd: 31094
  http: 38080