
image:
  repository: gitlab.desy.de:5555/dcache/dcache
  tag: ""
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent


dcache:
  numberOfCores: 2
  pools:
    - a
    - b
    - c 

cell:
  tunnel: 11111

door:
  ports:
    nfs: 2049
    dcapg: 22128
    dcap: 22125
    xrootd: 1094
    xrootdg: 1095
    webdav: 8080
    webdavs: 8083
    gridftp: 2811
    srm: 8443

mover:
  nfs: 32049
  xrootd: 31094
  http: 38080
  https: 38083
  wan_range_min: 28000
  wan_range_max: 28050