{{- range .Values.dcache.pools }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-pool-{{ . }}-certs-store
spec:
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteOnce
---
{{ end }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-door-certs-store
spec:
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteOnce

