apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-dcache-door
spec:
  selector:
    matchLabels:
      app: door
  replicas: 1
  serviceName: {{ .Release.Name }}-door-svc
  template:
    metadata:
      labels:
        app: door
    spec:
      containers:
      - name: dcache-door
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/run.sh", "{{ $.Release.Name }}-door-svc" ]
        readinessProbe:
          tcpSocket:
            port: 2049
          initialDelaySeconds: 90
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 2049
          initialDelaySeconds: 90
          timeoutSeconds: 5
        volumeMounts:
        - name: dcache-config
          mountPath: /opt/dcache/etc/dcache.conf
          subPath: dcache.conf
          readOnly: true
        - name: dcache-layout
          mountPath: /opt/dcache/etc/layouts/dcache-k8s.conf
          subPath: dcache-k8s.conf
          readOnly: true
        - name: init-scripts
          mountPath: /dcache.init.d/00-init.sh
          subPath: 00-init.sh
          readOnly: true
        - name: exports
          mountPath: /opt/dcache/etc/exports
          subPath: exports
          readOnly: true
        - name: certs
          mountPath: /opt/dcache/etc/certs
          readOnly: true
      initContainers:
        - securityContext:
            runAsUser: 0
            runAsGroup: 0
          name: init-host-certs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: AUTOCA_URL
              value: https://ci.dcache.org/ca
          command: ['sh', '-c', "curl --silent https://raw.githubusercontent.com/kofemann/autoca/v1.0-py3/pyclient/autoca-client -o /tmp/autoca-client; chmod a+x /tmp/autoca-client; cd /opt/dcache/var/tmp/; /tmp/autoca-client -n ${AUTOCA_URL} {{ $.Release.Name }}-door-svc; chown dcache:dcache *.pem"]
          volumeMounts:
            - mountPath: /opt/dcache/var/tmp/
              name: certs
      volumes:
      - name: certs
        persistentVolumeClaim:
          claimName: {{ $.Release.Name }}-door-certs-store
      - name: dcache-config
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "dcache.conf"
            path: "dcache.conf"
      - name: dcache-layout
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "dcache-k8s-door"
            path: "dcache-k8s.conf"
      - name: init-scripts
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "00-init.sh"
            path: "00-init.sh"
      - name: exports
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "export"
            path: "exports"
