apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-dcache-door
spec:
  selector:
    matchLabels:
      app: door
  replicas: 1
  serviceName: {{ .Release.Name }}-door-svc
  template:
    metadata:
      labels:
        app: door
    spec:
      containers:
      - name: dcache-door
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/run.sh", "{{ $.Release.Name }}-door-svc" ]
        readinessProbe:
          tcpSocket:
            port: 2049
          initialDelaySeconds: 90
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 2049
          initialDelaySeconds: 90
          timeoutSeconds: 5
        volumeMounts:
        - name: dcache-config
          mountPath: /opt/dcache/etc/dcache.conf
          subPath: dcache.conf
          readOnly: true
        - name: dcache-layout
          mountPath: /opt/dcache/etc/layouts/dcache-k8s.conf
          subPath: dcache-k8s.conf
          readOnly: true
        - name: init-scripts
          mountPath: /dcache.init.d/00-init.sh
          subPath: 00-init.sh
          readOnly: true
        - name: exports
          mountPath: /opt/dcache/etc/exports
          subPath: exports
          readOnly: true
        - name: gplazma-conf
          mountPath: /opt/dcache/etc/gplazma.conf
          subPath: gplazma.conf
          readOnly: true
        - name: grid-mapfile
          mountPath: /opt/dcache/etc/grid-mapfile
          subPath: grid-mapfile
          readOnly: true
        - name: vorolemap
          mountPath: /opt/dcache/etc/grid-vorolemap
          subPath: grid-vorolemap
          readOnly: true
        - name: storage-authzdb
          mountPath: /opt/dcache/etc/storage-authzdb
          subPath: storage-authzdb
          readOnly: true
        - name: certs
          mountPath: /etc/grid-security
          readOnly: true
      initContainers:
        - securityContext:
            runAsUser: 0
            runAsGroup: 0
          name: init-host-certs
          image: "centos:7"
          env:
            - name: AUTOCA_URL
              value: https://ci.dcache.org/ca
          command:
            - sh
            - -c
          args:
            - |
              yum install -y https://www.desy.de/~tigran/ca_dCacheORG-3.0-6.noarch.rpm https://linuxsoft.cern.ch/wlcg/centos7/x86_64/desy-voms-all-1.0.0-1.noarch.rpm https://repository.egi.eu/sw/production/cas/1/current/RPMS/ca_USERTrustRSACertificationAuthority-1.122-1.noarch.rpm https://repository.egi.eu/sw/production/cas/1/current/RPMS/ca_ResearchandEducationTrustRSARootCA-1.122-1.noarch.rpm https://repository.egi.eu/sw/production/cas/1/current/RPMS/ca_GEANTeScienceSSLCA4-1.122-1.noarch.rpm
              yum install -y python epel-release
              yum install -y fetch-crl
              curl --silent https://raw.githubusercontent.com/kofemann/autoca/v1.0-py2/pyclient/autoca-client -o /tmp/autoca-client;
              chmod a+x /tmp/autoca-client;
              cd /etc/grid-security/;
              /tmp/autoca-client -n ${AUTOCA_URL} {{ $.Release.Name }}-door-svc;
              chown 994:1000 *.pem;
              /usr/sbin/fetch-crl;
          volumeMounts:
            - mountPath: /etc/grid-security
              name: certs
      volumes:
      - name: certs
        persistentVolumeClaim:
          claimName: {{ $.Release.Name }}-door-certs-store
      - name: dcache-config
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "dcache.conf"
            path: "dcache.conf"
      - name: dcache-layout
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "dcache-k8s-door"
            path: "dcache-k8s.conf"
      - name: init-scripts
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "00-init.sh"
            path: "00-init.sh"
      - name: exports
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "export"
            path: "exports"
      - name: gplazma-conf
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "gplazma.conf"
            path: "gplazma.conf"
      - name: grid-mapfile
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "grid-mapfile"
            path: "grid-mapfile"
      - name: vorolemap
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "grid-vorolemap"
            path: "grid-vorolemap"
      - name: storage-authzdb
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "storage-authzdb"
            path: "storage-authzdb"
