apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-door-svc
  labels:
    app: door
spec:
  selector:
    app: door
  ports:
    - name: nfs-door
      port: {{ $.Values.door.ports.nfs }}
      targetPort: 2049
    - name: xroot-door
      port: {{ $.Values.door.ports.xrootd }}
      targetPort: 1094
    - name: xroot-door-gsi
      port: {{ $.Values.door.ports.xrootdg }}
      targetPort: 1095
    - name: webdav-door
      port: {{ $.Values.door.ports.webdav }}
      targetPort: 8080
    - name: webdavs-door
      port: {{ $.Values.door.ports.webdavs }}
      targetPort: 8083
    - name: dcapg-door
      port: {{ $.Values.door.ports.dcapg }}
      targetPort: 22128
    - name: dcap-door
      port: {{ $.Values.door.ports.dcap }}
      targetPort: 22125
    - name: gridftp-door
      port: {{ $.Values.door.ports.gridftp }}
      targetPort: 2811
    - name: srm-door
      port: {{ $.Values.door.ports.srm }}
      targetPort: 8443
    - name: cell-tunnel
      port: {{ $.Values.cell.tunnel }}
      targetPort: 11111
    {{ $range_start := ( $.Values.mover.wan_range_min | int) }}
    {{ $range_stop := ( $.Values.mover.wan_range_max | int) }}
    {{- range $port_index, $port := untilStep $range_start $range_stop 1 }}
    - name: wan-port-{{ $port_index }}
      port: {{ $port }}
      targetPort: {{ $port }}
    {{- end }}