apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-dcache-door
spec:
  selector:
    matchLabels:
      app: door
  replicas: 1
  serviceName: {{ .Release.Name }}-door-svc
  template:
    metadata:
      labels:
        app: door
    spec:
      containers:
      - name: dcache-door
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/run.sh", "door-svc" ]
        readinessProbe:
          tcpSocket:
            port: 2049
          initialDelaySeconds: 20
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 2049
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - name: dcache-config
          mountPath: /opt/dcache/etc/dcache.conf
          subPath: dcache.conf
          readOnly: true
        - name: dcache-layout
          mountPath: /opt/dcache/etc/layouts/dcache-k8s.conf
          subPath: dcache-k8s.conf
          readOnly: true
        - name: init-scripts
          mountPath: /dcache.init.d/00-init.sh
          subPath: 00-init.sh
          readOnly: true
        - name: exports
          mountPath: /opt/dcache/etc/exports
          subPath: exports
          readOnly: true
        - name: gplazma-conf
          mountPath: /opt/dcache/etc/gplazma.conf
          subPath: gplazma.conf
          readOnly: true
        - name: grid-mapfile
          mountPath: /opt/dcache/etc/grid-mapfile
          subPath: grid-mapfile
          readOnly: true
        - name: vorolemap
          mountPath: /opt/dcache/etc/grid-vorolemap
          subPath: grid-vorolemap
          readOnly: true
        - name: storage-authzdb
          mountPath: /opt/dcache/etc/storage-authzdb
          subPath: storage-authzdb
          readOnly: true
        - name: htpasswd
          mountPath: /opt/dcache/etc/htpasswd
          subPath: htpasswd
          readOnly: true
        - name: linkgroupauthz
          mountPath: /opt/dcache/etc/linkgroupauthz.conf
          subPath: linkgroupauthz.conf
          readOnly: true
        - name: certs
          mountPath: /etc/grid-security
          readOnly: true
      initContainers:
      {{ $host := print $.Release.Name "-door-svc."  $.Release.Namespace ".svc.cluster.local" -}}
      {{ include "dcache.certs.init" $host }}
          volumeMounts:
            - mountPath: /etc/grid-security
              name: certs
      volumes:
      - name: certs
        persistentVolumeClaim:
          claimName: {{ $.Release.Name }}-door-certs-store
      - name: dcache-config
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "dcache.conf"
            path: "dcache.conf"
      - name: dcache-layout
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "dcache-k8s-door"
            path: "dcache-k8s.conf"
      - name: init-scripts
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "00-init.sh"
            path: "00-init.sh"
      - name: exports
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "export"
            path: "exports"
      - name: gplazma-conf
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "gplazma.conf"
            path: "gplazma.conf"
      - name: grid-mapfile
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "grid-mapfile"
            path: "grid-mapfile"
      - name: vorolemap
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "grid-vorolemap"
            path: "grid-vorolemap"
      - name: storage-authzdb
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "storage-authzdb"
            path: "storage-authzdb"
      - name: htpasswd
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "htpasswd"
            path: "htpasswd"
      - name: linkgroupauthz
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "linkgroupauthz"
            path: "linkgroupauthz.conf"