{{- range .Values.dcache.pools }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-pool-{{ . }}
spec:
  selector:
    matchLabels:
      app: pool-{{ . }}
  replicas: 1
  serviceName: {{ $.Release.Name }}-pool-{{ . }}-svc
  template:
    metadata:
      labels:
        app: pool-{{ . }}
    spec:
      containers:
      - name: pool
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        command: ["/run.sh", "{{ $.Release.Name }}-pool-{{ . }}-svc"]
        readinessProbe:
          tcpSocket:
            port: {{ $.Values.mover.nfs }}
          initialDelaySeconds: 20
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: {{ $.Values.mover.nfs }}
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - name: dcache-config
          mountPath: /opt/dcache/etc/dcache.conf
          subPath: dcache.conf
          readOnly: true
        - name: dcache-layout
          mountPath: /opt/dcache/etc/layouts/dcache-k8s.conf
          subPath: dcache.conf
          readOnly: true
        - name: certs-store-{{ . }}
          mountPath: /etc/grid-security
          readOnly: true
      initContainers:
      {{ $host := print $.Release.Name  "-pool-" . "-svc." $.Release.Namespace ".svc.cluster.local" -}}
      {{ include "dcache.certs.init" $host }}
          volumeMounts:
            - mountPath: /etc/grid-security
              name: certs-store-{{ . }}
        - name: wait-for-core
          image: busybox:1.28
          command: ['sh', '-c', "until nc -z -v  {{ $.Release.Name }}-core-0.{{ $.Release.Namespace }}.svc.cluster.local {{ $.Values.cell.tunnel }}; do echo waiting for core to start; sleep 2; done"]
      volumes:
      - name: certs-store-{{ . }}
        persistentVolumeClaim:
          claimName: {{ $.Release.Name }}-pool-{{ . }}-certs-store
      - name: dcache-config
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "dcache.conf"
            path: "dcache.conf"
      - name: dcache-layout
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "config-pool-{{ . }}"
            path: "dcache.conf"
---
{{- end }}
