{{- range .Values.dcache.pools }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-pool-{{ . }}
spec:
  selector:
    matchLabels:
      app: pool-{{ . }}
  replicas: 1
  serviceName: {{ $.Release.Name }}-pool-{{ . }}-svc
  template:
    metadata:
      labels:
        app: pool-{{ . }}
    spec:
      containers:
      - name: pool
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        command: ["/run.sh", "{{ $.Release.Name }}-pool-{{ . }}-svc"]
        readinessProbe:
          tcpSocket:
            port: {{ $.Values.mover.nfs }}
          initialDelaySeconds: 20
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: {{ $.Values.mover.nfs }}
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - name: dcache-config
          mountPath: /opt/dcache/etc/dcache.conf
          subPath: dcache.conf
          readOnly: true
        - name: dcache-layout
          mountPath: /opt/dcache/etc/layouts/dcache-k8s.conf
          subPath: dcache.conf
          readOnly: true
        - name: certs-store-{{ . }}
          mountPath: /etc/grid-security
          readOnly: true
      initContainers:
        - securityContext:
            runAsUser: 0
            runAsGroup: 0
          name: init-host-certs
          image: "centos:7"
          env:
            - name: AUTOCA_URL
              value: https://ci.dcache.org/ca
          command:
            - sh
            - -c
          args:
            - |
              yum -q install -y openssl libtool-ltdl glibmm24 epel-release;
              yum -q install -y fetch-crl;
              rpm -i https://www.desy.de/~tigran/ca_dCacheORG-3.0-6.noarch.rpm;
              rpm -i https://linuxsoft.cern.ch/wlcg/centos7/x86_64/desy-voms-all-1.0.0-1.noarch.rpm;
              rpm -i https://repository.egi.eu/sw/production/cas/1/current/RPMS/ca_ResearchandEducationTrustRSARootCA-1.122-1.noarch.rpm;
              rpm -i https://repository.egi.eu/sw/production/cas/1/current/RPMS/ca_GEANTTCSAuthenticationRSACA4B-1.122-1.noarch.rpm;
              rpm -i https://repository.egi.eu/sw/production/cas/1/current/RPMS/ca_USERTrustRSACertificationAuthority-1.122-1.noarch.rpm;
              rpm -i https://repository.egi.eu/sw/production/cas/1/current/RPMS/ca_GEANTeScienceSSLCA4-1.122-1.noarch.rpm;
              rpm -i https://repository.egi.eu/sw/production/cas/1/current/RPMS/ca_USERTrustECCCertificationAuthority-1.122-1.noarch.rpm;
              rpm -i https://repository.egi.eu/sw/production/cas/1/current/RPMS/ca_GEANTeScienceSSLECCCA4-1.122-1.noarch.rpm;
              curl --silent https://raw.githubusercontent.com/kofemann/autoca/v1.0-py2/pyclient/autoca-client -o /tmp/autoca-client;
              chmod a+x /tmp/autoca-client;
              cd /etc/grid-security/;
              /tmp/autoca-client -n ${AUTOCA_URL} {{ $.Release.Name }}-pool-{{ . }}-svc.{{ $.Release.Namespace }}.svc.cluster.local;
              chown 994:1000 *.pem;
              /usr/sbin/fetch-crl;
          volumeMounts:
            - mountPath: /etc/grid-security
              name: certs-store-{{ . }}
        - name: wait-for-core
          image: busybox:1.28
          command: ['sh', '-c', "until nc -z -v  {{ $.Release.Name }}-door-svc.{{ $.Release.Namespace }}.svc.cluster.local {{ $.Values.cell.tunnel }}; do echo waiting for core to start; sleep 2; done"]
      volumes:
      - name: certs-store-{{ . }}
        persistentVolumeClaim:
          claimName: {{ $.Release.Name }}-pool-{{ . }}-certs-store
      - name: dcache-config
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "dcache.conf"
            path: "dcache.conf"
      - name: dcache-layout
        configMap:
          name: {{ $.Release.Name }}-configmap
          items:
          - key: "config-pool-{{ . }}"
            path: "dcache.conf"
---
{{- end }}
