{{- range .Values.dcache.pools }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-pool-{{ . }}
spec:
  selector:
    matchLabels:
      app: pool-{{ . }}
  replicas: 1
  serviceName: {{ $.Release.Name }}-pool-{{ . }}-svc
  template:
    metadata:
      labels:
        app: pool-{{ . }}
    spec:
      containers:
      - name: pool
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        command: ["/run.sh", "pool-{{ . }}-svc"]
        readinessProbe:
          tcpSocket:
            port: {{ $.Values.mover.nfs }}
          initialDelaySeconds: 20
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: {{ $.Values.mover.nfs }}
          initialDelaySeconds: 90
          timeoutSeconds: 5
        volumeMounts:
        {{ include "dcache.conf.mounts" . | indent 8 }}
        - name: certs-store-{{ . }}
          mountPath: /etc/grid-security
          readOnly: true
      initContainers:
      {{ $host := print $.Release.Name  "-pool-" . "-svc." $.Release.Namespace ".svc.cluster.local" -}}
      {{ include "dcache.certs.init" $host }}
          volumeMounts:
            - mountPath: /etc/grid-security
              name: certs-store-{{ . }}
        - name: wait-for-core
          image: busybox:1.28
          command: ['sh', '-c', "until nc -z -v  {{ $.Release.Name }}-door-svc.{{ $.Release.Namespace }}.svc.cluster.local {{ $.Values.cell.tunnel }}; do echo waiting for core to start; sleep 2; done"]
      volumes:
      {{ include "dcache.conf.volume" $ | indent 6 }}
      - name: certs-store-{{ . }}
        persistentVolumeClaim:
          claimName: {{ $.Release.Name }}-pool-{{ . }}-certs-store
---
{{- end }}
